import pandas as pd
import spacy
import os


def run_auto_labeler():
    """
    Processes the master_corpus.csv generated by CleanText_Fixed.py.
    Identifies entities and labels text chunks for NLP tasks.
    """
    input_file = "../data/processed_data/master_corpus.csv"
    output_file = "../data/processed_data/automated_labels.csv"

    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found. Run CleanText_Fixed.py first.")
        return

    print("Loading spaCy model (en_core_web_lg)...")
    nlp = spacy.load("en_core_web_lg")

    # SAFETY: Increase the max_length limit just in case,
    # though with chunked data we shouldn't hit it.
    nlp.max_length = 2000000

    print("Reading master corpus...")
    df = pd.read_csv(input_file)

    # We'll store new labels here
    entity_counts = []
    top_entities = []

    total_rows = len(df)
    print(f"Auto-labeling {total_rows} chunks...")

    # Iterate through each small chunk
    for i, text in enumerate(df['text']):
        # Standardize input
        if not isinstance(text, str):
            entity_counts.append(0)
            top_entities.append("")
            continue

        # Process the chunk with spaCy
        # This is now safe because 'text' is only ~7 sentences long
        doc = nlp(text)

        # Example Labeling: Count PERSON and GPE (Location) entities
        # This helps identify if a chunk is character-heavy or world-building
        entities = [ent.text for ent in doc.ents if ent.label_ in ["PERSON", "GPE"]]

        entity_counts.append(len(entities))
        top_entities.append(", ".join(entities[:3]))  # Store first 3 found

        # Progress indicator
        if (i + 1) % 500 == 0:
            print(f"   [{i + 1}/{total_rows}] chunks processed...")

    # Add new columns to our dataframe
    df['entity_count'] = entity_counts
    df['key_entities'] = top_entities

    print(f"Saving labeled data to {output_file}...")
    df.to_csv(output_file, index=False)
    print("SUCCESS!")


if __name__ == "__main__":
    run_auto_labeler()